import { defineConfig, coverageConfigDefaults } from "vitest/config";
import { fileURLToPath } from "node:url";
import react from "@vitejs/plugin-react";

const src = fileURLToPath(new URL("./src", import.meta.url));

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": src,
      "#": src,
      // `cloudflare:workers` is a Workers-runtime virtual module; stub it so
      // unit tests can import from modules that reference Cloudflare bindings.
      "cloudflare:workers": `${src}/__tests__/stubs/cloudflare-workers.ts`,
    },
  },
  test: {
    environment: "node",
    include: ["src/**/*.test.{ts,tsx}"],
    // Mock hygiene is global so no file has to hand-roll it — the version that
    // gets hand-rolled wrong fails silently. `vi.clearAllMocks()` in a local
    // beforeEach clears recorded CALLS but leaves the implementation installed,
    // so a one-off `mockRejectedValue` leaks into whichever test runs next
    // (#192 was exactly that, green only because the happy path was declared
    // first). `mockReset` restores a `vi.fn(impl)` to its original
    // implementation rather than blanking it, so `vi.mock` factories keep
    // working; `restoreMocks` undoes `vi.spyOn` so a stub cannot outlive the
    // test that installed it.
    mockReset: true,
    restoreMocks: true,
    // Randomise both the file order and the order within each file, so a test
    // that depends on a sibling running first fails now instead of on whatever
    // future PR happens to reorder it. #192 was that bug, and it survived
    // because the happy-path test was declared before the one that poisoned the
    // mock. Vitest prints the seed on every run — pass it back via
    // `--sequence.seed=<n>` to replay an order exactly.
    sequence: { shuffle: { files: true, tests: true } },
    // jsdom has no layout, so ProseMirror's scroll-into-view throws from a
    // deferred rAF and fails the run as an unhandled error. See the file.
    setupFiles: ["src/__tests__/setup.ts"],
    coverage: {
      // text for the terminal summary, lcov for the Codecov upload in CI.
      reporter: ["text", "lcov"],
      // `include` MUST stay pinned to every authored source file. Without it,
      // v8 reports only the modules a run happened to import, so the DENOMINATOR
      // moves with the import graph: a PR that adds one test importing a module
      // nothing else touched pulls that whole file in at ~0% and drops project
      // coverage on files the PR never opened. Measured on this repo: a test
      // whose only assertion was `typeof uploadFile === "function"` took the
      // total from 94.83% to 93.76% while covered statements stayed at exactly
      // 1910 — the 2014 → 2037 denominator growth was the entire delta. That is
      // the Codecov drift; pinning the file set is the fix.
      include: ["src/**/*.{ts,tsx}"],
      // Keep coverage about code we author and can meaningfully test:
      //   - components/ui: shadcn/Base UI vendored primitives
      //   - db/schema: declarative Drizzle table definitions, no logic
      //   - routeTree.gen.ts: generated by tsr
      //   - __tests__: test infrastructure (factories, harness) isn't product code
      //   - I18nProvider: context glue, deliberately untested (epic #95 decision)
      //   - router.tsx: router factory, only ever executed by the Start entry
      //   - lib/og/render.ts: the .wasm imports resolve in the worker build
      //     only, so the module cannot load under vitest at all (see the file)
      //   - routes/design-system.tsx: noindex living-styleguide page, in no nav
      // Everything else stays IN, `src/routes/**` included: the server-handler
      // routes are reachable through `Route.options.server.handlers` with a real
      // Request (see __tests__/server/mcp/route.test.ts), and a UI route's
      // validateSearch/head/loader are plain functions on `Route.options`.
      exclude: [
        ...coverageConfigDefaults.exclude,
        // Declaration files carry no executable code, and the explicit `include`
        // above matches them past the defaults.
        "src/**/*.d.ts",
        "src/components/ui/**",
        "src/db/schema/**",
        "src/routeTree.gen.ts",
        "src/__tests__/**",
        "src/i18n/I18nProvider.tsx",
        "src/router.tsx",
        "src/lib/og/render.ts",
        "src/routes/design-system.tsx",
      ],
    },
  },
});
