import { defineConfig, coverageConfigDefaults } from "vitest/config";
import { fileURLToPath } from "node:url";
import react from "@vitejs/plugin-react";

const src = fileURLToPath(new URL("./src", import.meta.url));

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": src,
      "#": src,
      // `cloudflare:workers` is a Workers-runtime virtual module; stub it so
      // unit tests can import from modules that reference Cloudflare bindings.
      "cloudflare:workers": `${src}/__tests__/stubs/cloudflare-workers.ts`,
    },
  },
  test: {
    environment: "node",
    include: ["src/**/*.test.{ts,tsx}"],
    coverage: {
      // Keep coverage about code we author and can meaningfully test:
      //   - components/ui: shadcn/Base UI vendored primitives
      //   - db/schema: declarative Drizzle table definitions, no logic
      //   - routeTree.gen.ts: generated by tsr
      exclude: [
        ...coverageConfigDefaults.exclude,
        "src/components/ui/**",
        "src/db/schema/**",
        "src/routeTree.gen.ts",
      ],
    },
  },
});
