/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteSlugRouteImport } from './routes/_site/$slug'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTagsRouteImport } from './routes/admin/tags'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as InterviewIndexRouteImport } from './routes/interview/index'
import { Route as SitePostsIndexRouteImport } from './routes/_site/posts/index'
import { Route as SitePostsSlugRouteImport } from './routes/_site/posts/$slug'
import { Route as SiteTagsIndexRouteImport } from './routes/_site/tags/index'
import { Route as AdminInterviewIndexRouteImport } from './routes/admin/interview/index'
import { Route as AdminInterviewSectionsRouteImport } from './routes/admin/interview/sections'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages/index'
import { Route as AdminPagesNewRouteImport } from './routes/admin/pages/new'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminPostsNewRouteImport } from './routes/admin/posts/new'
import { Route as InterviewSectionIndexRouteImport } from './routes/interview/$section/index'
import { Route as InterviewSectionSlugRouteImport } from './routes/interview/$section/$slug'
import { Route as AdminInterviewNotesIndexRouteImport } from './routes/admin/interview/notes/index'
import { Route as AdminInterviewNotesNewRouteImport } from './routes/admin/interview/notes/new'
import { Route as AdminPagesSlugEditRouteImport } from './routes/admin/pages/$slug/edit'
import { Route as AdminPostsPostIdEditRouteImport } from './routes/admin/posts/$postId/edit'
import { Route as ApiOgPagesSlugRouteImport } from './routes/api/og.pages.$slug'
import { Route as ApiOgPostsSlugRouteImport } from './routes/api/og.posts.$slug'
import { Route as AdminInterviewNotesNoteIdEditRouteImport } from './routes/admin/interview/notes/$noteId/edit'
import { Route as ApiOgInterviewSectSlugRouteImport } from './routes/api/og.interview.$sect.$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIndexRoute = InterviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InterviewRoute,
} as any)
const SitePostsIndexRoute = SitePostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => SiteRoute,
} as any)
const SitePostsSlugRoute = SitePostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTagsIndexRoute = SiteTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => SiteRoute,
} as any)
const AdminInterviewIndexRoute = AdminInterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInterviewSectionsRoute = AdminInterviewSectionsRouteImport.update({
  id: '/interview/sections',
  path: '/interview/sections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesNewRoute = AdminPagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const InterviewSectionIndexRoute = InterviewSectionIndexRouteImport.update({
  id: '/$section/',
  path: '/$section/',
  getParentRoute: () => InterviewRoute,
} as any)
const InterviewSectionSlugRoute = InterviewSectionSlugRouteImport.update({
  id: '/$section/$slug',
  path: '/$section/$slug',
  getParentRoute: () => InterviewRoute,
} as any)
const AdminInterviewNotesIndexRoute =
  AdminInterviewNotesIndexRouteImport.update({
    id: '/interview/notes/',
    path: '/interview/notes/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminInterviewNotesNewRoute = AdminInterviewNotesNewRouteImport.update({
  id: '/interview/notes/new',
  path: '/interview/notes/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesSlugEditRoute = AdminPagesSlugEditRouteImport.update({
  id: '/pages/$slug/edit',
  path: '/pages/$slug/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsPostIdEditRoute = AdminPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiOgPagesSlugRoute = ApiOgPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => ApiOgRoute,
} as any)
const ApiOgPostsSlugRoute = ApiOgPostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => ApiOgRoute,
} as any)
const AdminInterviewNotesNoteIdEditRoute =
  AdminInterviewNotesNoteIdEditRouteImport.update({
    id: '/interview/notes/$noteId/edit',
    path: '/interview/notes/$noteId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const ApiOgInterviewSectSlugRoute = ApiOgInterviewSectSlugRouteImport.update({
  id: '/interview/$sect/$slug',
  path: '/interview/$sect/$slug',
  getParentRoute: () => ApiOgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof SiteIndexRoute
  '/design-system': typeof DesignSystemRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/interview': typeof InterviewRouteWithChildren
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug': typeof SiteSlugRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/api/og': typeof ApiOgRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/interview/': typeof InterviewIndexRoute
  '/posts/$slug': typeof SitePostsSlugRoute
  '/admin/interview/sections': typeof AdminInterviewSectionsRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/interview/$section/$slug': typeof InterviewSectionSlugRoute
  '/posts/': typeof SitePostsIndexRoute
  '/tags/': typeof SiteTagsIndexRoute
  '/admin/interview/': typeof AdminInterviewIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/interview/$section/': typeof InterviewSectionIndexRoute
  '/admin/interview/notes/new': typeof AdminInterviewNotesNewRoute
  '/admin/pages/$slug/edit': typeof AdminPagesSlugEditRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/api/og/pages/$slug': typeof ApiOgPagesSlugRoute
  '/api/og/posts/$slug': typeof ApiOgPostsSlugRoute
  '/admin/interview/notes/': typeof AdminInterviewNotesIndexRoute
  '/admin/interview/notes/$noteId/edit': typeof AdminInterviewNotesNoteIdEditRoute
  '/api/og/interview/$sect/$slug': typeof ApiOgInterviewSectSlugRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof DesignSystemRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$slug': typeof SiteSlugRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/api/og': typeof ApiOgRouteWithChildren
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/interview': typeof InterviewIndexRoute
  '/posts/$slug': typeof SitePostsSlugRoute
  '/admin/interview/sections': typeof AdminInterviewSectionsRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/interview/$section/$slug': typeof InterviewSectionSlugRoute
  '/posts': typeof SitePostsIndexRoute
  '/tags': typeof SiteTagsIndexRoute
  '/admin/interview': typeof AdminInterviewIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/interview/$section': typeof InterviewSectionIndexRoute
  '/admin/interview/notes/new': typeof AdminInterviewNotesNewRoute
  '/admin/pages/$slug/edit': typeof AdminPagesSlugEditRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/api/og/pages/$slug': typeof ApiOgPagesSlugRoute
  '/api/og/posts/$slug': typeof ApiOgPostsSlugRoute
  '/admin/interview/notes': typeof AdminInterviewNotesIndexRoute
  '/admin/interview/notes/$noteId/edit': typeof AdminInterviewNotesNoteIdEditRoute
  '/api/og/interview/$sect/$slug': typeof ApiOgInterviewSectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/interview': typeof InterviewRouteWithChildren
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/$slug': typeof SiteSlugRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/api/og': typeof ApiOgRouteWithChildren
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/interview/': typeof InterviewIndexRoute
  '/_site/posts/$slug': typeof SitePostsSlugRoute
  '/admin/interview/sections': typeof AdminInterviewSectionsRoute
  '/admin/pages/new': typeof AdminPagesNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/interview/$section/$slug': typeof InterviewSectionSlugRoute
  '/_site/posts/': typeof SitePostsIndexRoute
  '/_site/tags/': typeof SiteTagsIndexRoute
  '/admin/interview/': typeof AdminInterviewIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/interview/$section/': typeof InterviewSectionIndexRoute
  '/admin/interview/notes/new': typeof AdminInterviewNotesNewRoute
  '/admin/pages/$slug/edit': typeof AdminPagesSlugEditRoute
  '/admin/posts/$postId/edit': typeof AdminPostsPostIdEditRoute
  '/api/og/pages/$slug': typeof ApiOgPagesSlugRoute
  '/api/og/posts/$slug': typeof ApiOgPostsSlugRoute
  '/admin/interview/notes/': typeof AdminInterviewNotesIndexRoute
  '/admin/interview/notes/$noteId/edit': typeof AdminInterviewNotesNoteIdEditRoute
  '/api/og/interview/$sect/$slug': typeof ApiOgInterviewSectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/design-system'
    | '/feed.xml'
    | '/interview'
    | '/mcp'
    | '/sitemap.xml'
    | '/$slug'
    | '/admin/settings'
    | '/admin/tags'
    | '/api/og'
    | '/admin/'
    | '/interview/'
    | '/posts/$slug'
    | '/admin/interview/sections'
    | '/admin/pages/new'
    | '/admin/posts/new'
    | '/interview/$section/$slug'
    | '/posts/'
    | '/tags/'
    | '/admin/interview/'
    | '/admin/pages/'
    | '/admin/posts/'
    | '/interview/$section/'
    | '/admin/interview/notes/new'
    | '/admin/pages/$slug/edit'
    | '/admin/posts/$postId/edit'
    | '/api/og/pages/$slug'
    | '/api/og/posts/$slug'
    | '/admin/interview/notes/'
    | '/admin/interview/notes/$noteId/edit'
    | '/api/og/interview/$sect/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design-system'
    | '/feed.xml'
    | '/mcp'
    | '/sitemap.xml'
    | '/$slug'
    | '/admin/settings'
    | '/admin/tags'
    | '/api/og'
    | '/'
    | '/admin'
    | '/interview'
    | '/posts/$slug'
    | '/admin/interview/sections'
    | '/admin/pages/new'
    | '/admin/posts/new'
    | '/interview/$section/$slug'
    | '/posts'
    | '/tags'
    | '/admin/interview'
    | '/admin/pages'
    | '/admin/posts'
    | '/interview/$section'
    | '/admin/interview/notes/new'
    | '/admin/pages/$slug/edit'
    | '/admin/posts/$postId/edit'
    | '/api/og/pages/$slug'
    | '/api/og/posts/$slug'
    | '/admin/interview/notes'
    | '/admin/interview/notes/$noteId/edit'
    | '/api/og/interview/$sect/$slug'
  id:
    | '__root__'
    | '/admin'
    | '/_site'
    | '/design-system'
    | '/feed.xml'
    | '/interview'
    | '/mcp'
    | '/sitemap.xml'
    | '/_site/$slug'
    | '/admin/settings'
    | '/admin/tags'
    | '/api/og'
    | '/_site/'
    | '/admin/'
    | '/interview/'
    | '/_site/posts/$slug'
    | '/admin/interview/sections'
    | '/admin/pages/new'
    | '/admin/posts/new'
    | '/interview/$section/$slug'
    | '/_site/posts/'
    | '/_site/tags/'
    | '/admin/interview/'
    | '/admin/pages/'
    | '/admin/posts/'
    | '/interview/$section/'
    | '/admin/interview/notes/new'
    | '/admin/pages/$slug/edit'
    | '/admin/posts/$postId/edit'
    | '/api/og/pages/$slug'
    | '/api/og/posts/$slug'
    | '/admin/interview/notes/'
    | '/admin/interview/notes/$noteId/edit'
    | '/api/og/interview/$sect/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  InterviewRoute: typeof InterviewRouteWithChildren
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOgRoute: typeof ApiOgRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/$slug': {
      id: '/_site/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/': {
      id: '/interview/'
      path: '/'
      fullPath: '/interview/'
      preLoaderRoute: typeof InterviewIndexRouteImport
      parentRoute: typeof InterviewRoute
    }
    '/_site/posts/': {
      id: '/_site/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof SitePostsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/posts/$slug': {
      id: '/_site/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof SitePostsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tags/': {
      id: '/_site/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof SiteTagsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/interview/': {
      id: '/admin/interview/'
      path: '/interview'
      fullPath: '/admin/interview/'
      preLoaderRoute: typeof AdminInterviewIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/interview/sections': {
      id: '/admin/interview/sections'
      path: '/interview/sections'
      fullPath: '/admin/interview/sections'
      preLoaderRoute: typeof AdminInterviewSectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/new': {
      id: '/admin/pages/new'
      path: '/pages/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AdminPagesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/interview/$section/': {
      id: '/interview/$section/'
      path: '/$section'
      fullPath: '/interview/$section/'
      preLoaderRoute: typeof InterviewSectionIndexRouteImport
      parentRoute: typeof InterviewRoute
    }
    '/interview/$section/$slug': {
      id: '/interview/$section/$slug'
      path: '/$section/$slug'
      fullPath: '/interview/$section/$slug'
      preLoaderRoute: typeof InterviewSectionSlugRouteImport
      parentRoute: typeof InterviewRoute
    }
    '/admin/interview/notes/': {
      id: '/admin/interview/notes/'
      path: '/interview/notes'
      fullPath: '/admin/interview/notes/'
      preLoaderRoute: typeof AdminInterviewNotesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/interview/notes/new': {
      id: '/admin/interview/notes/new'
      path: '/interview/notes/new'
      fullPath: '/admin/interview/notes/new'
      preLoaderRoute: typeof AdminInterviewNotesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/$slug/edit': {
      id: '/admin/pages/$slug/edit'
      path: '/pages/$slug/edit'
      fullPath: '/admin/pages/$slug/edit'
      preLoaderRoute: typeof AdminPagesSlugEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/$postId/edit': {
      id: '/admin/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/admin/posts/$postId/edit'
      preLoaderRoute: typeof AdminPostsPostIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/og/pages/$slug': {
      id: '/api/og/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/api/og/pages/$slug'
      preLoaderRoute: typeof ApiOgPagesSlugRouteImport
      parentRoute: typeof ApiOgRoute
    }
    '/api/og/posts/$slug': {
      id: '/api/og/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/api/og/posts/$slug'
      preLoaderRoute: typeof ApiOgPostsSlugRouteImport
      parentRoute: typeof ApiOgRoute
    }
    '/admin/interview/notes/$noteId/edit': {
      id: '/admin/interview/notes/$noteId/edit'
      path: '/interview/notes/$noteId/edit'
      fullPath: '/admin/interview/notes/$noteId/edit'
      preLoaderRoute: typeof AdminInterviewNotesNoteIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/og/interview/$sect/$slug': {
      id: '/api/og/interview/$sect/$slug'
      path: '/interview/$sect/$slug'
      fullPath: '/api/og/interview/$sect/$slug'
      preLoaderRoute: typeof ApiOgInterviewSectSlugRouteImport
      parentRoute: typeof ApiOgRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInterviewSectionsRoute: typeof AdminInterviewSectionsRoute
  AdminPagesNewRoute: typeof AdminPagesNewRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminInterviewIndexRoute: typeof AdminInterviewIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminInterviewNotesNewRoute: typeof AdminInterviewNotesNewRoute
  AdminPagesSlugEditRoute: typeof AdminPagesSlugEditRoute
  AdminPostsPostIdEditRoute: typeof AdminPostsPostIdEditRoute
  AdminInterviewNotesIndexRoute: typeof AdminInterviewNotesIndexRoute
  AdminInterviewNotesNoteIdEditRoute: typeof AdminInterviewNotesNoteIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInterviewSectionsRoute: AdminInterviewSectionsRoute,
  AdminPagesNewRoute: AdminPagesNewRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminInterviewIndexRoute: AdminInterviewIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminInterviewNotesNewRoute: AdminInterviewNotesNewRoute,
  AdminPagesSlugEditRoute: AdminPagesSlugEditRoute,
  AdminPostsPostIdEditRoute: AdminPostsPostIdEditRoute,
  AdminInterviewNotesIndexRoute: AdminInterviewNotesIndexRoute,
  AdminInterviewNotesNoteIdEditRoute: AdminInterviewNotesNoteIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SiteRouteChildren {
  SiteSlugRoute: typeof SiteSlugRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SitePostsSlugRoute: typeof SitePostsSlugRoute
  SitePostsIndexRoute: typeof SitePostsIndexRoute
  SiteTagsIndexRoute: typeof SiteTagsIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteSlugRoute: SiteSlugRoute,
  SiteIndexRoute: SiteIndexRoute,
  SitePostsSlugRoute: SitePostsSlugRoute,
  SitePostsIndexRoute: SitePostsIndexRoute,
  SiteTagsIndexRoute: SiteTagsIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface InterviewRouteChildren {
  InterviewIndexRoute: typeof InterviewIndexRoute
  InterviewSectionSlugRoute: typeof InterviewSectionSlugRoute
  InterviewSectionIndexRoute: typeof InterviewSectionIndexRoute
}

const InterviewRouteChildren: InterviewRouteChildren = {
  InterviewIndexRoute: InterviewIndexRoute,
  InterviewSectionSlugRoute: InterviewSectionSlugRoute,
  InterviewSectionIndexRoute: InterviewSectionIndexRoute,
}

const InterviewRouteWithChildren = InterviewRoute._addFileChildren(
  InterviewRouteChildren,
)

interface ApiOgRouteChildren {
  ApiOgPagesSlugRoute: typeof ApiOgPagesSlugRoute
  ApiOgPostsSlugRoute: typeof ApiOgPostsSlugRoute
  ApiOgInterviewSectSlugRoute: typeof ApiOgInterviewSectSlugRoute
}

const ApiOgRouteChildren: ApiOgRouteChildren = {
  ApiOgPagesSlugRoute: ApiOgPagesSlugRoute,
  ApiOgPostsSlugRoute: ApiOgPostsSlugRoute,
  ApiOgInterviewSectSlugRoute: ApiOgInterviewSectSlugRoute,
}

const ApiOgRouteWithChildren = ApiOgRoute._addFileChildren(ApiOgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  InterviewRoute: InterviewRouteWithChildren,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOgRoute: ApiOgRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
